package lk.ijse.tailorshop.util;

public enum TextField {
CUSTOMERID,ADDRESS,EMAIL,MATERIALID,QTY,UNITPRICE,EMPLOYEEID,MEASUREMENTID,NECKSIZE,ARMHOLE,SLEEVELENGTH,WRIST,CHEST,TORSOLENGTH,
    WAIST,HIP,CROTCHLENGTH,SHOULDERWIDTH,THIGHCIRCUMFERENCE,WAISTTOHEM,DUEDATE,USERID,PAYMENTID,TOTALCOST,AMOUNT,BALANCE,MATERIALCOST,
    TOWAGE,TOTALPRICE,QTYONHAND,ORDERQTY,PLACEORDERQTY

}
